# Generated by Django 6.0.6 on 2026-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='excellent_score',
            field=models.PositiveIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_score',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
