# Generated by Django 6.0.6 on 2026-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('happy', '开心'), ('cool', '冷漠'), ('learning', '学习中'), ('busy', '忙碌'), ('resting', '休息中'), ('charging', '充电中')], default='learning', max_length=20),
        ),
    ]
