# Generated by Django 6.0.6 on 2026-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('happy', '开心'), ('cool', '冷漠'), ('learning', '学习中'), ('focused', '专注中'), ('reading', '阅读中'), ('practicing', '实践中'), ('thinking', '思考中'), ('examing', '备考中'), ('asking', '求助中'), ('busy', '忙碌'), ('resting', '休息中'), ('charging', '充电中')], default='learning', max_length=20),
        ),
    ]
