# Generated by Django 6.0.6 on 2026-07-08 09:54

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_communitypostlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_posts/', validators=[apps.common.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='learning_resources/', validators=[apps.common.validators.validate_image]),
        ),
    ]
