# Generated by Django 6.0.6 on 2026-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_communitypost_image_learningresource_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='preview_site_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
