# Generated by Django 6.0.6 on 2026-07-08 13:06

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_learningresource_preview_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='learning_resource_attachments/', validators=[apps.common.validators.validate_material]),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
